# Generated by Django 2.0.5 on 2018-05-05 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='datos',
            name='tipo',
            field=models.CharField(choices=[('entra', 'Entra'), ('sale', 'Sale')], max_length=255),
        ),
    ]
