# Generated by Django 2.0.5 on 2018-05-05 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_personas_is_active'),
        ('fotos', '0002_fotos_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotos',
            name='personas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personas.Personas'),
        ),
    ]
