# Generated by Django 2.0.5 on 2018-05-05 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
