# Generated by Django 2.0.5 on 2018-05-05 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0002_auto_20180505_0027'),
        ('personas', '0002_personas_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='datos',
            field=models.ManyToManyField(to='datos.Datos'),
        ),
    ]
