# Generated by Django 2.0.5 on 2018-05-19 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_personas_datos'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='tarjeta_uid',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
